# Ansible Inventory — Auto-generated by Terraform
# Do NOT edit manually. Re-run 'terraform apply' to regenerate.

[all:vars]
ansible_ssh_private_key_file=${ssh_key_path}
ansible_python_interpreter=/usr/bin/python3

[control]
%{ for name, inst in control ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

[workers]
%{ for name, inst in workers ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

[ubuntu]
%{ for name, inst in ubuntu ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

[redhat]
%{ for name, inst in redhat ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

[amazon]
%{ for name, inst in amazon ~}
${name} ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}
